import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Sidenav from "./Sidenav";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

        
      <body className={inter.className + "shadow-md w-screen h-screen"}>
        
        <div className=" flex justify-start items-center space-x-10 bg-blue-500 py-4 md:px-10 px-7 ">
        <Sidenav/>
        
        <a href="/#">
        
          <Image src={`/logo2.png`}  alt=""  height={10} width={50}  />
        </a>
        
          <Link
            href="/#"
            className="text-xl  
              font-bold  
              hover:underline   
              hover:text-red-500  
              inline-block  
              hover:duration-300  
              cursor-pointer">Home
          </Link>
          <Link
            href="/about"
            className="text-xl  
              font-bold  
              hover:underline   
              hover:text-red-500  
              inline-block  
              hover:duration-300  
              cursor-pointer"
          >
            About
          </Link>
          <Link
            href="/service"
            className="text-xl  
              font-bold  
              hover:underline   
              hover:text-red-500  
              inline-block  
              hover:duration-300  
              cursor-pointer"
          >
            Service
          </Link>
          <Link
            href="/teams"
            className="text-xl  
              font-bold  
              hover:underline   
              hover:text-red-500  
              inline-block  
              hover:duration-300  
              cursor-pointer"
          >
            Teams
          </Link>
        </div>
        
        <main>{children}</main>
      </body>
    </html>
  );
}
